Hw07 file copying
DaryaPe/hw-test pull request #7
Opened 2023-05-08 12:23 UTC by DaryaPe

## Домашнее задание №7 «Утилита для копирования файлов»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я провел ручное тестирование программы (например, запускал `test.sh`).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2023-05-08 17:48 UTC, dshemin requested changes

2023-05-08 17:48 UTC, dshemin commented on hw07_file_copying/go.mod
> +module github.com/DaryaPe/hw07_file_copying
Критично:

Должно быть `github.com/DaryaPe/hw-test/hw07_file_copying`

2023-05-08 17:48 UTC, dshemin commented on hw07_file_copying/copy_test.go
> +		ff, _ := os.ReadFile(fromFile)
Важно:

Не игнорируйте ошибки даже в тестах. Потом будет сложно понять почему тест упал.

2023-05-08 17:48 UTC, dshemin commented on hw07_file_copying/copy.go
> +func validateFileParams(fromPath, toPath string) error {
Важно:

Нет проверки на то, что fromPath и toPath указывают на один и тот же файл.

2023-05-08 17:48 UTC, dshemin commented on hw07_file_copying/copy.go
> +	bar.Finish()
Важно:

Лучше в defer

2023-05-09 13:43 UTC, DaryaPe commented on hw07_file_copying/go.mod
> +module github.com/DaryaPe/hw07_file_copying
Исправила

2023-05-09 13:43 UTC, DaryaPe commented on hw07_file_copying/copy_test.go
> +		ff, _ := os.ReadFile(fromFile)
Добавила обработчики.

2023-05-09 13:43 UTC, DaryaPe commented on hw07_file_copying/copy.go
> +func validateFileParams(fromPath, toPath string) error {
Добавила проверку.

2023-05-09 13:43 UTC, DaryaPe commented on hw07_file_copying/copy.go
> +	bar.Finish()
Исправила.

2023-05-09 17:16 UTC, dshemin approved these changes

2023-05-09 17:16 UTC, dshemin commented on hw07_file_copying/copy.go
> +	if fromPath == toPath {
Важно:

С точки зрения сравнения строк, пути `/foo/bar` и `/foo/../foo/bar` разные, а с точки зрения файловой системы указывают на один файл.

2023-05-10 05:45 UTC, DaryaPe commented on hw07_file_copying/copy.go
> +	if fromPath == toPath {
Точно! Исправила.

2023-05-10 10:33 UTC, dshemin approved these changes

2023-05-10 10:45 UTC, merged