Hw09 struct validator
DaryaPe/hw-test pull request #9
Opened 2023-12-02 21:34 UTC by DaryaPe

## Домашнее задание №9 «Валидатор структур»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)

### Критерии оценки
- [ ] Пайплайн зелёный - 3 балла
- [ ] Добавлены юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 3 баллов

#### Зачёт от 7 баллов

2023-12-02 23:55 UTC, dshemin requested changes

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	msgExpectedStruct = "expected struct but returned %s value"
Важно:

Такое можно сделать в виде констант.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	msgExpectedStruct = "expected struct but returned %s value"
Важно:

Не лучшее решение вытаскивать шаблоны строк. Такое довольно тяжело поддерживать.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	errInternal   = fmt.Errorf("internal error")
Важно:

Для создания константных ошибок лучше использовать errors.New

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var result string
Важно:

Для сборки строк надо использовать strings.Builder -  более эффективное решение.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		field := value.Field(i)
Критично:

Нет проверки на то, что текущее поле - публичное.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	var err error
Важно:

Надо либо убрать данную переменную, либо внутри case убрать проверку на err != nil  и в конце функции просто оставить `return err`. В циклах, если произошла ошибка, делать break.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +		if err != nil && errors.Is(err, errInternal) {
Важно:

Тут можно просто `if errors.Is(err, errInternal)`.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	if len(v.validationErrs) > 0 {
Важно:

Лучше просто вернуть `v.validationErrs` и дать вызывающему коду возможность с ней работать так, как ему это будет надо.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Важно:

Сильно громоздко получается, проще в начале сделать проверку что это не строка и вернуть ошибку, а потом валидировать.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Важно:

Сильно громоздко получается, проще в начале сделать проверку что это не строка и вернуть ошибку, а потом валидировать.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Важно:

Сильно громоздко получается, проще в начале сделать проверку что это не число и вернуть ошибку, а потом валидировать.

2023-12-02 23:55 UTC, dshemin commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Важно:

Сильно громоздко получается, проще в начале сделать проверку что это не число и вернуть ошибку, а потом валидировать.

2023-12-03 08:15 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	msgExpectedStruct = "expected struct but returned %s value"
Исправлено

2023-12-03 08:15 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	errInternal   = fmt.Errorf("internal error")
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	var result string
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +		field := value.Field(i)
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	var err error
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	if len(v.validationErrs) > 0 {
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Исправлено

2023-12-03 08:16 UTC, DaryaPe commented on hw09_struct_validator/validator.go
> +	switch value.Kind() { //nolint:exhaustive
Исправлено

2023-12-03 11:15 UTC, dshemin approved these changes

2023-12-03 11:19 UTC, merged